### ISSUE TITLE
bamToMethylationCalls.py crashed

### ISSUE THREAD

**Issue by cgeisenberger** [BuysDB/SingleCellMultiOmics#147]
command run via *qsub*: 

`bamToMethylationCalls.py -bin_size 1 -threads 4 -bismark_tabfile out.bed test.bam`

error message:

```
Traceback (most recent call last):
  File "/hpc/hub_oudenaarden/bdebarbanson/virtualEnvironments/py36/bin/bamToMethylationCalls.py", line 177, in <module>
    bf = counts.get_bulk_frame()
  File "/hpc/hub_oudenaarden/bdebarbanson/virtualEnvironments/py36/lib/python3.6/site-packages/singlecellmultiomics/methylation/methylation.py", line 172, in get_bulk_frame
    return pd.DataFrame(mat, index=pd.MultiIndex.from_tuples(columns),
  File "/hpc/hub_oudenaarden/bdebarbanson/virtualEnvironments/py36/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 477, in from_tuples
    raise TypeError(msg)
TypeError: Cannot infer number of levels from empty list
```

**Comment by BuysDB** [comment]
I think it is caused by the file being empty or not containing reads tagged by bamtagmultiome
