### ISSUE TITLE
libraryStatistics crash

### ISSUE THREAD

**Issue by marapara** [BuysDB/SingleCellMultiOmics#63]
After using updated demux.py and mapping with bowtie2

Not plotting rejection reasons, rejection tag RR was never seen
Not making a plot for TrimmingStats as no plot method is defined
-bash-4.2$ cat cluster/25_11_2019_15_48_26-STATE8-13S-CB6-K27m3-190315-2.stderr
[E::hts_open_format] Failed to open file None
Traceback (most recent call last):
  File "/hpc/hub_oudenaarden/bdebarbanson/virtualEnvironments/py36/bin/bamPlotRTstats.py", line 83, in <module>
    with pysam.AlignmentFile(args.bamFile) as a:
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 940, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `None`: No such file or directory
/hpc/hub_oudenaarden/bdebarbanson/virtualEnvironments/py36/lib/python3.6/site-packages/seaborn/matrix.py:603: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  metric=self.metric)

**Comment by marloes3105** [comment]
In addition, for the scars:

Not plotting rejection reasons, rejection tag RR was never seen
Not making a plot for TrimmingStats as no plot method is defined
Traceback (most recent call last):
  File "/hpc/hub_oudenaarden/Marloes/miniconda3/envs/conda/bin/bamPlotRTstats.py", line 86, in <module>
    a, umi_hamming_distance=1)):
  File "/hpc/hub_oudenaarden/Marloes/miniconda3/envs/conda/lib/python3.6/site-packages/singlecellmultiomics/universalBamTagger/universalBamTagger.py", line 377, in __iter__
    molecule_id = self.assignment_function(fragment)
  File "/hpc/hub_oudenaarden/Marloes/miniconda3/envs/conda/lib/python3.6/site-packages/singlecellmultiomics/universalBamTagger/universalBamTagger.py", line 300, in assignment_function
    'RX'), fragment[0].get_tag('RS')
  File "pysam/libcalignedsegment.pyx", line 2395, in pysam.libcalignedsegment.AlignedSegment.get_tag
  File "pysam/libcalignedsegment.pyx", line 2437, in pysam.libcalignedsegment.AlignedSegment.get_tag
KeyError: "tag 'RX' not present"

**Comment by BuysDB** [comment]
This has been fixed, the problem was the name of the tagged bam file. It will now also look for ./tagged/tagged.bam
