### ISSUE TITLE
RT stats, do not process files which don't have UMI information

### ISSUE THREAD

**Issue by BuysDB** [BuysDB/SingleCellMultiOmics#64]
In addition, for the scars:

Not plotting rejection reasons, rejection tag RR was never seen
Not making a plot for TrimmingStats as no plot method is defined
Traceback (most recent call last):
  File "/hpc/hub_oudenaarden/Marloes/miniconda3/envs/conda/bin/bamPlotRTstats.py", line 86, in <module>
    a, umi_hamming_distance=1)):
  File "/hpc/hub_oudenaarden/Marloes/miniconda3/envs/conda/lib/python3.6/site-packages/singlecellmultiomics/universalBamTagger/universalBamTagger.py", line 377, in __iter__
    molecule_id = self.assignment_function(fragment)
  File "/hpc/hub_oudenaarden/Marloes/miniconda3/envs/conda/lib/python3.6/site-packages/singlecellmultiomics/universalBamTagger/universalBamTagger.py", line 300, in assignment_function
    'RX'), fragment[0].get_tag('RS')
  File "pysam/libcalignedsegment.pyx", line 2395, in pysam.libcalignedsegment.AlignedSegment.get_tag
  File "pysam/libcalignedsegment.pyx", line 2437, in pysam.libcalignedsegment.AlignedSegment.get_tag
KeyError: "tag 'RX' not present"

_Originally posted by @marloes3105 in https://github.com/BuysDB/SingleCellMultiOmics/issues/63#issuecomment-559492002_

**Comment by BuysDB** [comment]
It is impossible to make a RT plot without umi information. You can prevent `libraryStatistics.py` from trying to make this plot by supplying `--nort`
